/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FclinicaGUI;

import javax.swing.JOptionPane;

/**
 *
 * @author lg
 */
public class Mallampati extends javax.swing.JFrame {
    
    private FclinicaGUI telaMae;
    private int finalfis;
    private int finalcognitivo;
    private int finalpsico;
    private int finaltotal;
    //private boolean boxusado;
    private int ScoreFisico[];
    private int ScoreCognitivo[];
    private int ScorePsico[];
    private int ScoreTotal[];
    /**
     * Creates new form Mallampati
     */
    private int porcentagem(int numero, int max){
        int total;
        total = (numero * 100)/max;
        return total;
    }
    
    private void atualizaTotal(int indice, int valor){
        ScoreTotal[indice-1] = valor;
        finaltotal = 0;
        
        for(int i = 0; i < ScoreTotal.length; i++){
            finaltotal += ScoreTotal[i];
        }
        tfTotalPercent.setText(Integer.toString(porcentagem(finaltotal, 84)));
        tfTotalNum.setText(Integer.toString(finaltotal));
    }
    private void atualizaFisico(int indice, int valor){
       ScoreFisico[indice] = valor;
       finalfis = 0;
       
       for(int i = 0; i < ScoreFisico.length; i++){
           finalfis += ScoreFisico[i];
       }
       tfFisicoPercent.setText(Integer.toString(porcentagem(finalfis, 36))+ '%');
       tfFisicoNum.setText(Integer.toString(finalfis));
       atualizaTotal(1, finalfis);
   }
    private void atualizaCognitivo(int indice, int valor){
        ScoreCognitivo[indice] = valor;
        finalcognitivo = 0;
        
        for(int i = 0; i < ScoreCognitivo.length; i++){
            finalcognitivo += ScoreCognitivo[i];
        }
        tfCognitivoPercent.setText(Integer.toString(porcentagem(finalcognitivo, 40))+'%');
        tfCognitivoNormal.setText(Integer.toString(finalcognitivo));
        atualizaTotal(2, finalcognitivo);
    }
    private void atualizaPsico(int indice, int valor){
        ScorePsico[indice] = valor;
        finalpsico = 0;
        
        for(int i = 0; i < ScorePsico.length; i++){
            finalpsico += ScorePsico[i];
        }
        tfPsicossocialPercent.setText(Integer.toString(porcentagem(finalpsico, 8))+'%');
        tfPsicossocialNum.setText(Integer.toString(finalpsico));
        atualizaTotal(3, finalpsico);
    }
    //MUDAR ESSA PORRA
   public Mallampati(FclinicaGUI telaAnterior) {
        //boxusado =false;
        initComponents();
        ScoreFisico = new int[9];
        ScoreCognitivo = new int[10];
        ScorePsico = new int[2];
        ScoreTotal = new int[3];
        telaMae = telaAnterior;
        telaMae.setEnabled(false);
        
        for(int i = 0; i < ScoreTotal.length; i++){
            ScoreTotal[i] = 0;
        }
        for(int i = 0; i < ScoreFisico.length; i++){
           ScoreFisico[i] = 0;
        }
        for(int i = 0; i < ScoreCognitivo.length; i++){
            ScoreCognitivo[i] = 0;
        }
        for(int i = 0; i < ScorePsico.length; i++){
            ScorePsico[i] = 0;
        }

   }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        tf7 = new javax.swing.JTextField();
        tf8 = new javax.swing.JTextField();
        tf9 = new javax.swing.JTextField();
        tf10 = new javax.swing.JTextField();
        tf12 = new javax.swing.JTextField();
        tf13 = new javax.swing.JTextField();
        tf14 = new javax.swing.JTextField();
        tf15 = new javax.swing.JTextField();
        tf16 = new javax.swing.JTextField();
        tf17 = new javax.swing.JTextField();
        tf18 = new javax.swing.JTextField();
        tf19 = new javax.swing.JTextField();
        tf20 = new javax.swing.JTextField();
        tf21 = new javax.swing.JTextField();
        tf11 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfFisicoPercent = new javax.swing.JTextField();
        tfFisicoNum = new javax.swing.JTextField();
        tfCognitivoPercent = new javax.swing.JTextField();
        tfCognitivoNormal = new javax.swing.JTextField();
        tfPsicossocialPercent = new javax.swing.JTextField();
        tfPsicossocialNum = new javax.swing.JTextField();
        tfTotalPercent = new javax.swing.JTextField();
        tfTotalNum = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1 - Eu tenho estado menos atento: ");

        jLabel2.setText("2 - Eu tenho dificuldade para prestar atenção por longos períodos: ");

        jLabel3.setText("3 - Eu tenho sido incapaz de pensar claramente: ");

        jLabel4.setText("4 - Eu tenho sido desajeitado e descoordenado:");

        jLabel5.setText("5 - Eu tenho estado esquecido:");

        jLabel6.setText("6 - Eu tenho tido que me adequar a minhas atividades físicas:");

        jLabel7.setText("7 - Eu tenho estado menos motivado para fazer qualquer coisa que requer esforço físico:");

        jLabel8.setText("8 - Eu tenho estado menos motivado para participar de atividades sociais:");

        jLabel9.setText("9 - Eu estado limitado nas minhas habilidades para fazer coisas fora de casa:");

        jLabel10.setText("10 - Eu tenho tido dificuldades para manter esforço fisico por longos períodos:");

        jLabel11.setText("11- Eu tenho tido dificuldades para tomar decisões:");

        jLabel12.setText("12 - Eu tenho estado menos motivado para fazer algo que requer pensar:");

        jLabel13.setText("13 - Meus músculos tem sentido fraqueza:");

        jLabel14.setText("14 - Eu tenho estado desconfortável:");

        jLabel15.setText("15 - Eu tenho tido dificuldade em terminar tarefas que requerem esforço para pensar:");

        jLabel16.setText("16 - Eu tenho tido dificuldades em organizar meus pensamentos quando estou fazendo coisas em casa ou no trabalho:");

        jLabel17.setText("17 - Eu tenho estado menos capaz de completar tarefas que requerem esforço físico:");

        jLabel18.setText("18 - Meu pensamento tem estado mais lento:");

        jLabel19.setText("19 - Eu tenho tido dificuldade de concentração:");

        jLabel20.setText("20 - Eu tenho limitação nas minhas atividades físicas:");

        jLabel21.setText("21 - Eu tenho precisado descansar por mais frequencia ou por longos períodos;");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf1FocusLost(evt);
            }
        });

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        tf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf2FocusLost(evt);
            }
        });

        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3actionperformed(evt);
            }
        });
        tf3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf3FocusLost(evt);
            }
        });

        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4actionperformed(evt);
            }
        });
        tf4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf4FocusLost(evt);
            }
        });

        tf5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf5FocusLost(evt);
            }
        });

        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });
        tf6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf6FocusLost(evt);
            }
        });

        tf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf7ActionPerformed(evt);
            }
        });
        tf7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf7FocusLost(evt);
            }
        });

        tf8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf8ActionPerformed(evt);
            }
        });
        tf8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf8FocusLost(evt);
            }
        });

        tf9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf9ActionPerformed(evt);
            }
        });
        tf9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf9FocusLost(evt);
            }
        });

        tf10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf10FocusLost(evt);
            }
        });

        tf12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf12ActionPerformed(evt);
            }
        });
        tf12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf12FocusLost(evt);
            }
        });

        tf13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf13ActionPerformed(evt);
            }
        });
        tf13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf13FocusLost(evt);
            }
        });

        tf14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf14ActionPerformed(evt);
            }
        });
        tf14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf14FocusLost(evt);
            }
        });

        tf15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf15ActionPerformed(evt);
            }
        });
        tf15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf15FocusLost(evt);
            }
        });

        tf16.setToolTipText("");
        tf16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf16ActionPerformed(evt);
            }
        });
        tf16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf16FocusLost(evt);
            }
        });

        tf17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf17ActionPerformed(evt);
            }
        });
        tf17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf17FocusLost(evt);
            }
        });

        tf18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf18ActionPerformed(evt);
            }
        });
        tf18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf18FocusLost(evt);
            }
        });

        tf19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf19ActionPerformed(evt);
            }
        });
        tf19.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf19FocusLost(evt);
            }
        });

        tf20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf20ActionPerformed(evt);
            }
        });
        tf20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf20FocusLost(evt);
            }
        });

        tf21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf21ActionPerformed(evt);
            }
        });
        tf21.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf21FocusLost(evt);
            }
        });

        tf11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf11ActionPerformed(evt);
            }
        });
        tf11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf11FocusLost(evt);
            }
        });

        jLabel22.setText("Resultados:");

        jLabel23.setText("Físico:");

        jLabel24.setText("Cognitivo:");

        jLabel25.setText("Psicossocial:");

        jLabel26.setText("Total:");

        tfFisicoPercent.setEditable(false);
        tfFisicoPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFisicoPercentActionPerformed(evt);
            }
        });

        tfFisicoNum.setEditable(false);
        tfFisicoNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFisicoNumActionPerformed(evt);
            }
        });

        tfCognitivoPercent.setEditable(false);
        tfCognitivoPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCognitivoPercentActionPerformed(evt);
            }
        });

        tfCognitivoNormal.setEditable(false);
        tfCognitivoNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCognitivoNormalActionPerformed(evt);
            }
        });

        tfPsicossocialPercent.setEditable(false);
        tfPsicossocialPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPsicossocialPercentActionPerformed(evt);
            }
        });

        tfPsicossocialNum.setEditable(false);
        tfPsicossocialNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPsicossocialNumActionPerformed(evt);
            }
        });

        tfTotalPercent.setEditable(false);
        tfTotalPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalPercentActionPerformed(evt);
            }
        });

        tfTotalNum.setEditable(false);
        tfTotalNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalNumActionPerformed(evt);
            }
        });

        jButton1.setText("OK!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfTotalPercent)
                                            .addComponent(tfPsicossocialPercent, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfCognitivoPercent, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfFisicoPercent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfPsicossocialNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfTotalNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(174, 174, 174)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfFisicoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfCognitivoNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel22)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf1)
                                    .addComponent(tf2)
                                    .addComponent(tf3)
                                    .addComponent(tf4)
                                    .addComponent(tf5)
                                    .addComponent(tf6)
                                    .addComponent(tf7)
                                    .addComponent(tf8)
                                    .addComponent(tf9)
                                    .addComponent(tf10)
                                    .addComponent(tf11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11))))
                        .addGap(8, 8, 8)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(tf14)
                            .addComponent(tf15)
                            .addComponent(tf16)
                            .addComponent(tf17)
                            .addComponent(tf18)
                            .addComponent(tf19)
                            .addComponent(tf12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf20)
                            .addComponent(tf21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(tf12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(tf13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(tf14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(tf15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(tf16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(tf17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(tf18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(tf19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(tf20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(tf21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tf7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(tf8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(tf9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(tf11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(tfFisicoPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfFisicoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(tfCognitivoPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCognitivoNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(tfPsicossocialPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPsicossocialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(tfTotalPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTotalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
        );

        tf1.getAccessibleContext().setAccessibleName("");

        jLabel27.setText("0 = Nunca  |  1 = Raramente  |   2 = Poucas vezes  |   3 = Muitas vezes  |   4 = Sempre  ");
        jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel27))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// <editor-fold defaultstate="collapsed" desc="EVENTOS NAO UTILIZADOS">
    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
 /*       try {
            int numero = Integer.parseInt(tf1.getText());
            if(!VerificaEntrada(numero)){
                JOptionPane.showMessageDialog(this, "Entrada inválida, O número deve estar entre 0 e 3!");
               }
            else{
                //atualizascore(0,numero);               
        }
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Entrada inválida!");
       }*/ 
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void tf9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf9ActionPerformed
/*         try {
            int numero = Integer.parseInt(tf9.getText());
            if(!VerificaEntrada(numero)){
                JOptionPane.showMessageDialog(this, "Entrada inválida, O número deve estar entre 0 e 3!");
               }
            else{
                atualizascore(2,numero);               
        }
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Entrada inválida!");
        }*/
    }//GEN-LAST:event_tf9ActionPerformed

    private void tf3actionperformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3actionperformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3actionperformed

    private void tf4actionperformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4actionperformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf4actionperformed

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf6ActionPerformed

    private void tf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf7ActionPerformed

    private void tf8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf8ActionPerformed
/*         try {
            int numero = Integer.parseInt(tf8.getText());
            if(!VerificaEntrada(numero)){
                JOptionPane.showMessageDialog(this, "Entrada inválida, O número deve estar entre 0 e 3!");
               }
            else{
                atualizascore(2,numero);               
        }
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Entrada inválida!");
        }*/
    }//GEN-LAST:event_tf8ActionPerformed

    private void tf12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf12ActionPerformed

    private void tf13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf13ActionPerformed

    private void tf14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf14ActionPerformed

    private void tf15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf15ActionPerformed

    private void tf16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf16ActionPerformed

    private void tf17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf17ActionPerformed

    private void tf18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf18ActionPerformed

    private void tf19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf19ActionPerformed

    private void tf20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf20ActionPerformed

    private void tf21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf21ActionPerformed

    private void tf11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf11ActionPerformed

    private void tfFisicoPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFisicoPercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFisicoPercentActionPerformed

    private void tfCognitivoPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCognitivoPercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCognitivoPercentActionPerformed

    private void tfPsicossocialPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPsicossocialPercentActionPerformed
      
        
    }//GEN-LAST:event_tfPsicossocialPercentActionPerformed

    private void tfTotalPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalPercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalPercentActionPerformed

    private void tfFisicoNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFisicoNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFisicoNumActionPerformed

    private void tfCognitivoNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCognitivoNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCognitivoNormalActionPerformed

    private void tfPsicossocialNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPsicossocialNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPsicossocialNumActionPerformed

    private void tfTotalNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalNumActionPerformed
//</editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        telaMae.AtualizaMallampati(finaltotal);
        telaMae.setEnabled(true);
        telaMae.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusLost
        int resposta;
        resposta = Integer.parseInt(tf1.getText());
         if(resposta > 4) {
            resposta = 4;
            tf1.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf1.setText(Integer.toString(0));
        }
         atualizaCognitivo(0, resposta);
    }//GEN-LAST:event_tf1FocusLost

    private void tf2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusLost
        int resposta;
        resposta = Integer.parseInt(tf2.getText());
         if(resposta > 4) {
            resposta = 4;
            tf2.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf2.setText(Integer.toString(0));
        }
         atualizaCognitivo(1, resposta);
    }//GEN-LAST:event_tf2FocusLost

    private void tf3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf3FocusLost
        int resposta;
        resposta = Integer.parseInt(tf3.getText());
         if(resposta > 4) {
            resposta = 4;
            tf3.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf3.setText(Integer.toString(0));
        }
         atualizaCognitivo(2, resposta);
    }//GEN-LAST:event_tf3FocusLost

    private void tf5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf5FocusLost
        int resposta;
        resposta = Integer.parseInt(tf5.getText());
         if(resposta > 4) {
            resposta = 4;
            tf5.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf5.setText(Integer.toString(0));
        }
         atualizaCognitivo(3, resposta);
    }//GEN-LAST:event_tf5FocusLost

    private void tf11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf11FocusLost
        int resposta;
        resposta = Integer.parseInt(tf11.getText());
         if(resposta > 4) {
            resposta = 4;
            tf11.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf11.setText(Integer.toString(0));
        }
         atualizaCognitivo(4, resposta);
    }//GEN-LAST:event_tf11FocusLost

    private void tf12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf12FocusLost
        int resposta;
        resposta = Integer.parseInt(tf12.getText());
         if(resposta > 4) {
            resposta = 4;
            tf12.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf12.setText(Integer.toString(0));
        }
         atualizaCognitivo(5, resposta);
    }//GEN-LAST:event_tf12FocusLost

    private void tf15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf15FocusLost
        int resposta;
        resposta = Integer.parseInt(tf15.getText());
         if(resposta > 4) {
            resposta = 4;
            tf15.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf15.setText(Integer.toString(0));
        }
         atualizaCognitivo(6, resposta);
    }//GEN-LAST:event_tf15FocusLost

    private void tf16FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf16FocusLost
        int resposta;
        resposta = Integer.parseInt(tf16.getText());
         if(resposta > 4) {
            resposta = 4;
            tf16.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf16.setText(Integer.toString(0));
        }
         atualizaCognitivo(7, resposta);
    }//GEN-LAST:event_tf16FocusLost

    private void tf18FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf18FocusLost
        int resposta;
        resposta = Integer.parseInt(tf18.getText());
         if(resposta > 4) {
            resposta = 4;
            tf18.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf18.setText(Integer.toString(0));
        }
         atualizaCognitivo(8, resposta);
    }//GEN-LAST:event_tf18FocusLost

    private void tf19FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf19FocusLost
        int resposta;
        resposta = Integer.parseInt(tf19.getText());
         if(resposta > 4) {
            resposta = 4;
            tf19.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf19.setText(Integer.toString(0));
        }
         atualizaCognitivo(9, resposta);
    }//GEN-LAST:event_tf19FocusLost

    private void tf4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf4FocusLost
        int resposta;
        resposta = Integer.parseInt(tf4.getText());
         if(resposta > 4) {
            resposta = 4;
            tf4.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf4.setText(Integer.toString(0));
        }
         atualizaFisico(0, resposta);
    }//GEN-LAST:event_tf4FocusLost

    private void tf6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf6FocusLost
        int resposta;
        resposta = Integer.parseInt(tf6.getText());
         if(resposta > 4) {
            resposta = 4;
            tf6.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf6.setText(Integer.toString(0));
        }
         atualizaFisico(1, resposta);
    }//GEN-LAST:event_tf6FocusLost

    private void tf7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf7FocusLost
        int resposta;
        resposta = Integer.parseInt(tf7.getText());
         if(resposta > 4) {
            resposta = 4;
            tf7.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf7.setText(Integer.toString(0));
        }
         atualizaFisico(2, resposta);
    }//GEN-LAST:event_tf7FocusLost

    private void tf10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf10FocusLost
        int resposta;
        resposta = Integer.parseInt(tf10.getText());
         if(resposta > 4) {
            resposta = 4;
            tf10.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf10.setText(Integer.toString(0));
        }
         atualizaFisico(3, resposta);
    }//GEN-LAST:event_tf10FocusLost

    private void tf13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf13FocusLost
        int resposta;
        resposta = Integer.parseInt(tf13.getText());
         if(resposta > 4) {
            resposta = 4;
            tf13.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf13.setText(Integer.toString(0));
        }
         atualizaFisico(4, resposta);
    }//GEN-LAST:event_tf13FocusLost

    private void tf14FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf14FocusLost
        int resposta;
        resposta = Integer.parseInt(tf14.getText());
         if(resposta > 4) {
            resposta = 4;
            tf14.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf14.setText(Integer.toString(0));
        }
         atualizaFisico(5, resposta);
    }//GEN-LAST:event_tf14FocusLost

    private void tf17FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf17FocusLost
        int resposta;
        resposta = Integer.parseInt(tf17.getText());
         if(resposta > 4) {
            resposta = 4;
            tf17.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf17.setText(Integer.toString(0));
        }
         atualizaFisico(6, resposta);
    }//GEN-LAST:event_tf17FocusLost

    private void tf20FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf20FocusLost
        int resposta;
        resposta = Integer.parseInt(tf20.getText());
         if(resposta > 4) {
            resposta = 4;
            tf20.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf20.setText(Integer.toString(0));
        }
         atualizaFisico(7, resposta);
    }//GEN-LAST:event_tf20FocusLost

    private void tf21FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf21FocusLost
        int resposta;
        resposta = Integer.parseInt(tf21.getText());
         if(resposta > 4) {
            resposta = 4;
            tf21.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf21.setText(Integer.toString(0));
        }
         atualizaFisico(8, resposta);
    }//GEN-LAST:event_tf21FocusLost

    private void tf8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf8FocusLost
        int resposta;
        resposta = Integer.parseInt(tf8.getText());
         if(resposta > 4) {
            resposta = 4;
            tf8.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf8.setText(Integer.toString(0));
        }
         atualizaPsico(0, resposta);
    }//GEN-LAST:event_tf8FocusLost

    private void tf9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf9FocusLost
        int resposta;
        resposta = Integer.parseInt(tf9.getText());
         if(resposta > 4) {
            resposta = 4;
            tf9.setText(Integer.toString(4));
        }
         if(resposta < 0) {
            resposta = 0;
            tf9.setText(Integer.toString(0));
        }
         atualizaPsico(1, resposta);
    }//GEN-LAST:event_tf9FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mallampati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mallampati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mallampati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mallampati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf10;
    private javax.swing.JTextField tf11;
    private javax.swing.JTextField tf12;
    private javax.swing.JTextField tf13;
    private javax.swing.JTextField tf14;
    private javax.swing.JTextField tf15;
    private javax.swing.JTextField tf16;
    private javax.swing.JTextField tf17;
    private javax.swing.JTextField tf18;
    private javax.swing.JTextField tf19;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf20;
    private javax.swing.JTextField tf21;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    private javax.swing.JTextField tfCognitivoNormal;
    private javax.swing.JTextField tfCognitivoPercent;
    private javax.swing.JTextField tfFisicoNum;
    private javax.swing.JTextField tfFisicoPercent;
    private javax.swing.JTextField tfPsicossocialNum;
    private javax.swing.JTextField tfPsicossocialPercent;
    private javax.swing.JTextField tfTotalNum;
    private javax.swing.JTextField tfTotalPercent;
    // End of variables declaration//GEN-END:variables
}